### ISSUE TITLE
Mostrar Letra

### ISSUE THREAD

**Issue by JoseVarelaP** [JoseVarelaP/Sazzer#7]
Dependiendo del archivo de audio, debe ser posible obtener la información de la letra de la canción, o por algún sistema externo como un API, obtener la letra de la canción en cuestión para mostrarla al usuario.

No hay una manera completamente nativa para obtener la letra directamente del archivo de audio, pero es posible obtenerla directamente sin necesidad de usar algún tipo de API, pero no estoy seguro de cuál método utilizar.

@zuleluis @rpsaul10 ¿Qué opciones piensan para tratar con este problema?

**Comment by rpsaul10** [comment]
Pues yo estuve investigando y yo creo que la mejor forma de obtener la letra de la canción es con una API, según ví con Musixmatch, solo nos registramos y nos da una URL, y podemos hacer consultas con el nombre de la canción y el artista

**Comment by rpsaul10** [comment]
Si el audio no contiene esto en sus metadatos pues se le pone un mensaje al usuario que nos es posible obtener la letra de ese archivo

**Comment by JoseVarelaP** [comment]
Con el PR #11 , ya se muestra la letra con la aplicación. Solamente tenemos la limitación del 30% de la letra, pero está justificado en el documento.
